#!/bin/bash

grep '<td>.*</td>'|
sed "/<td><[/]td>/d"|
sed "s/<[/]*td>//g"|
sed '1~2d'|

tr '[A-Z]' '[a-z]'|

sed "s/<[/]*u>//g"|

sed "s/\`/\'/g"|

sed "s/,/\n/g" |
sed "s/\s/\n/g" |

sed "/[^pk'mnwlhaeiou]/d"|

sort -u
